### ISSUE TITLE
[FEATURE] US tenant support

### ISSUE THREAD

**Issue by e46lux** [Pyhass/Hive-Custom-Component#102]
**Is your feature request related to a problem? Please describe.**
Unable to fully connect to US tenant. This is what I see in the logs:
"Hive token has expired when calling https://beekeeper.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true - HTTP status is - 401"

**Describe the solution you'd like**
Possibly a drop down selection during integration setup that lets you choose the US tenant? Or auto-detection.

**Describe alternatives you've considered**
Attempted editing python scripts to change beekeper.hivehome.com URLs to beekeper-us.hivehome.com, with some success (different error) but unclear which entries need to point to beeker-us.hivehome.com - the token part, I could not get to function.

**Additional context**
Comparing logs for US vs UK connections using dev tools in the network log, these are the only entries I see that connect to beekeper-us.hivehome.com:
<img width="770" alt="beekeper-us" src="https://user-images.githubusercontent.com/84468340/118884461-1de76b00-b8bc-11eb-9efe-ec9c2acf2a60.png">

The following are pinged for updates:
<img width="742" alt="beekeper-us-ping" src="https://user-images.githubusercontent.com/84468340/118884832-92baa500-b8bc-11eb-8f9b-771b52ea7b6c.png">

**Comment by KJonline** [comment]
@e46lux what website do you login to is that different to the UK one?

**Comment by e46lux** [comment]
@KJonline the login is going through the same https://my.hivehome.com/ login (https://sso.hivehome.com/?client=v3-web-prod&redirect=https://my.hivehome.com landing page).

I have an account on the UK tenant and I can login to either account using the same webpage - the only difference is some requests are going to beeker-us.hivehome.com (with -us after beeker).

**Comment by KJonline** [comment]
When you say token issues, how far have you go with python can you login? Refresh tokens? Get data with the us url?

**Comment by e46lux** [comment]
@KJonline I've been trying to reverse engineer the login but I'm not sure how I can actually go through and debug it by myself step-by-step. It looks like I'm also getting an unable to authenticate using my UK tenant account just like the US tenant. Is there a way I can get more granular debugging turned on? I have these in my configuration.yaml:

logger:
    pyhiveapi: debug
    custom_components.pyscript: info

however, all I'm getting is Success! Created configuration for xxx@xxx.com during integration setup and instant log entry that only says:
Config entry 'xxx@xxx.xxx' for hive integration could not authenticate

The integration screen says: Failed to set up: could not authenticate.

The way I updated the URLs in previous version in my initial testing to change the login URL was to edit the entries in /usr/local/lib/python3.8/site-packages/pyhiveapi/api/hive_api.py
I changed the "base" entry and unfortunately I did not make notes in my original testing, but I believe I attempted updating the "login" entry as well. Changing these in this latest version does not change the outcome.

**Comment by KJonline** [comment]
@e46lux that file you have referenced is the sync version of the api. Home Assistant uses the async version so it would be async_hive_api.py that would need to be modified.

The best way to capture how requests are made and what the urls are is by using a HTTP capture on your mobile device and capture the URL's through that for iOS I use a app called Charles which you do have to pay for. But from what I have seen can get free versions from similar applications.

Once you capture the urls you then need to export them, I think the login is using the API's as the uk one, its either returning a different response or request another URL which is invalid.

**Comment by e46lux** [comment]
@KJonline I've mitm the login and changing mode. I redacted some identifying information, and apologize for the long dump, but here is what I am seeing (POST, GET and their HTTP responses):

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/exxxxxxxxxxxxxxxxxxx
HTTP/2.0 200

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxx
HTTP/2.0 200 

POST https://cognito-idp.eu-west-1.amazonaws.com/ {"ChallengeName":"PASSWORD_VERIFIER","ChallengeParameters":{"SALT":".........."}}

HTTP/2.0 200 
:authority cognito-idp.eu-west-1.amazonaws.com
{"AuthFlow":"USER_SRP_AUTH","ClientId":"............


POST https://cognito-idp.eu-west-1.amazonaws.com/ {"ChallengeName":"PASSWORD_VERIFIER","ClientId":"xxxxxxxxxxx","ChallengeResponses":{"USERNAME":"xxxxxxxx","PASSWORD_CLAIM_SECRET_BLOCK":"...."}}}

HTTP/2.0 200 {"AuthenticationResult":{"AccessToken":"....."}

POST https://cognito-idp.eu-west-1.amazonaws.com/ {"AccessToken":"....."}

HTTP/2.0 200 {"UserAttributes":[{"Name":"sub","Value":"xxxxxxxxx"},{"Name":"zoneinfo","Value":"xxxxxx"},{"Name":"email_verified","Value":"true"},{"Name":"phone_number_verified","Value":"false"},{"Name":"locale","Value":"en_US"},{"Name":"given_name","Value":"Don"},{"Name":"custom:location","Value":"us-east-1"},{"Name":"custom:environment","Value":"de-prod"},{"Name":"email","Value":"xxxxxxxxxx"}],"Username":"xxxxxxxxxxxx"}

GET https://beekeeper-us.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true&user=true&homes=true&homeId authorization
xxxxxxxxxxxxxxxxxxxxxxxxx

HTTP/2.0 200 x-amz-cf-pop	xxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxx
{
    "actions": [],
    "alerts": {
        "failuresEmail": false,
        "failuresSMS": false,
        "nightAlerts": false,
        "warningsEmail": false,
        "warningsSMS": false
    },
    "devices": [
        {
            "created": xxxxxxx,
            "id": "xxxxxxxxxxxxxxxxxxx",
            "lastSeen": xxxxxxxxxxxx,
            "parent": "xxxxxxxxxxxxxxxxxxx",
            "props": {
                "assistedLiving": {
                    "learning": true,
                    "nightTime": false,
                    "noMorningActivity": false,
                    "noRecentActivity": false
                },
                "capabilities": [
								
GET https://beekeeper-us.hivehome.com/1.0/action-templates?version=3 authorization xxxxxxxxxxxxxx accept-encoding gzip

HTTP/2.0 200 
x-amz-apigw-id	xxxxxxxxxxx
etag	xxxxxxxxxxxxa
x-amzn-trace-id	Root=1-xxxxxxxxxxxxxx;Sampled=1
access-control-allow-credentials	true
x-cache	Miss from cloudfront
via	1.1 xxxxxxxxxx.cloudfront.net (CloudFront)
x-amz-cf-pop	xxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxxxxxx
{
    "ETag": "xxxxxxxxxxxxxxxxxx",
    "modified": "2020-08-18T14:27:22.846Z",
    "templates": [
        {
            "created": 1xxxxxxxxx,
            "entitlements": [],

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN0102xxxxx7/s2502xxxxx 
Host	centricabritishgas.sc.omtrdc.net
Connection	Keep-Alive
Accept-Encoding	gzip
ndh:             1
pev2:            AMACTION:login
ce:              UTF-8
ts:              xxxxxxxxxxxxxx
c.:              
tapMFAToggle.:   
status:          OFF
.tapMFAToggle:   
HTTP/1.1 200 OK xserver	anedge-xxxxxxxxxx-w4fdg
access-control-allow-origin	*
x-c	main-1475.xxxxxxxx.M0-497

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN010xxxxxxxx/s6654xxxxx
ndh:             1
ce:              UTF-8
ts:              1xxxxxxxxxx0
c.:              
tapMFAToggle.:   
status:          OFF

HTTP/1.1 200 OK

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxx/attributes/app-settings authorization xxxxxxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop	xxxxx
x-amz-cf-id	xxxxxxxxxxxxxx
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxxxxx": 30,
    "lastboostduration-cool-xxxxxxxx": 60,
    "lastboostduration-heat-xxxxxxxxxxx": 60,
    "lastboosttarget-cool-xxxxxxxxxx": 23,

GET https://hive-app-service-text.hivehome.net/prod/us.json :authority	hive-app-service-text.hivehome.net
HTTP/2.0 404 

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxx/attributes/entitlements authorization xxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop	xxxxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxx
{
    "MimicMode": true,
    "flags": {}
}

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxx/attributes/dashboard-config :authority: beekeeper-us.hivehome.com
authorization: xxxxxxxxxxx
HTTP/2.0 404 {
    "error": "NOT_FOUND"
}

POST https://api.de-prod.nacho.tech/omnia/deviceTokens/ authorization Bearer xxxxxxxxxxxxxx
{
    "deviceTokens": [
        {
            "appName": "Android_Hive_Live_GCM",
            "token": "xxxxxxxxxxxxxx",
            "tokenType": "GCM_DATA"
        }
    ]
}
HTTP/2.0 200 server	Jetty(9.4.35.v20201120)
{"meta":{},"links":{},"linked":{},"deviceTokens":[{"id":"xxxxxxxxxxxxxx","href":"https://api.de-prod.nacho.tech/omnia/deviceTokens/xxxxxxxxxx","token":"xxxxxxxxxxxx","tokenType":"GCM_DATA","appName":"Android_Hive_Live_GCM"}]}

GET https://hive.bgchprod.info/permission/document?encode=false authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 200 {
    "Identities": null,
    "Permissions": [
        "omnia-api:node:xxxxxxxxxxxxx:MIGRATE_HUB",
        "home-service:home:xxxxxxxxxxxx:ADD_EXTERNAL_USER",
        "home-service:home:xxxxxxxxxxxx:INVITE_USERS",

GET https://hive.bgchprod.info/home/home/1xxxxxxxxxxxxxa/tariffs  authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 200 access-control-allow-credentials	true
x-cache	Miss from cloudfront
x-amz-cf-pop	xxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxxxxxxx
{
    "home": "xxxxxxxxxxxxxx",
    "tariffs": []
}

GET https://hive.bgchprod.info/heating-costs/subscription/xxxxxxxxxxxx  authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 403  {
    "Message": "There is no subscription to Heating Cost Calculator for homeID xxxxxxxxxxxxxx"
}

GET https://beekeeper-us.hivehome.com/1.0/security-lite?homeId=xxxxxxxxxxxx authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 404  x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxx
{
    "error": "NOT_FOUND"
}

POST https://beekeeper-us.hivehome.com/1.0/app-update
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxx
{
    "os": 23,
    "platform": "react-native-android",
    "version": "10.41.1"
}
HTTP/2.0 200 {
    "type": "ok"
}

GET https://in-app-sales.hivehome.net/production/config-v3.json
:authority	in-app-sales.hivehome.net
HTTP/2.0 200 {
    "gb": {
        "cacheTTLHours": 1,
        "defaultShopUrl": "www.hivehome.com?cid=cen.in-app.in-life....shop",
        "deliveryOptions": [
            {
                "basketTotalMax": 49.99,
                "basketTotalMin": 0,
                "description": "3-5 working days",
                "hasHiveLive": false,
                "id": "delivery-1",
                "productRatePlanId": "xxxxxxxxxx",
                "ratePlanRef": "DEL00005"


POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxx/attributes/app-settings :authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxxxxxxxx": 30,
HTTP/2.0 200 x-amz-cf-id	xxxxxxxxxxxxxxxx
{
    "attribute": "app-settings",
    "value": {       
		    "feature-usage-devices.settings-changeNameSuccesful": true,
        "feature-usage-heating.settings-changeNameSuccesful": true,
        "first-time-customisation-modal": true,

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN01xxxxx/sxxxxx4
ndh:             1
ce:              UTF-8
ts:              xxxxxxxxx
c.:              
tapMFAToggle.:   
status:          OFF
.tapMFAToggle:   
accessibility:   none
hdl.:            
platform.:       
environment:     production
os:              android
version:         10.41.1
technology:      react-native
.platform:       
user.:           
defaultCountry:  US
id:              xxxxxxxxxxxxx
defaultPostcode: xxxxx
HTTP/1.1 200 OK

GET https://in-app-sales.hivehome.net/production/images.json
:authority	in-app-sales.hivehome.net
HTTP/2.0 200 x-amz-cf-id	xxxxxxxxxxxxxxxx
{
    "accessory/signal_booster/single.png": "https://d3orhbv7fx766b.cloudfront.net/accessory/signal_booster/single-61c4c4af5ec7f464b4219dcea7d078e3b1780fad8bc0d1c9e02f39453d838380.png",

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxxxxx
:authority	logs.hivehome-prod.bgchtest.info
accept-encoding	gzip
0000000000 1f 8b 08 00 c1 4b b5 60 00 03 dd 5a 5b 73 a3 36   .....K.`...Z[s.6
HTTP/2.0 200 apigw-requestid	xxxxxxxx

GET https://hive.bgchprod.info/home/owner/882cd8bb-b50f-4a5d-9cd1-cce5d462ea1b/home/id/13feddf0-9ff8-4ec3-85bd-ed855cd8eb7a
authorization Bearer xxxxxxxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop	xxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxx
{
    "address": "xxxxxxxxxxxxxx",
    "environment": "prod-us",
    "home": "xxxxxxxxxxxxxxxx",
    "homePhase": "Live",
    "homePicture": null,
    "homeTypes": [
        "HIVE"
    ],
    "homeUsers": {
        "OWNER": [
            "xxxxxxxxxx"

GET https://hive.bgchprod.info/home/home/xxxxxxxxxx/user_access
authorization Bearer xxxxxxxxxxxxxxx
HTTP/2.0 200 
{
    "disarmSchedules": {},
    "home": "xxxxxxxxxxxxx",
    "permissionPolicies": {
        "xxxxxxxxxxxxx": []
    },
    "pinIds": {
        "xxxxxxxxxxxxxxxx": null
    },
    "pins": {}
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxx
HTTP/2.0 200

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxx?homeId=xxxxxxxx
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxx
{
    "controlMode": "AUTO"
}

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN0102xxxx/s5xxxxxxx Host	centricabritishgas.sc.omtrdc.net
ndh:             1
ce:              UTF-8
ts:              xxxxxxxx
c.:              
tapMFAToggle.:   
status:          OFF
HTTP/1.1 200 OK

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN01020xxxxx/sxxxxx Host	centricabritishgas.sc.omtrdc.net
ndh:             1
ce:              UTF-8
ts:              162xxxxxx
c.:              
tapMFAToggle.:   
status:          OFF
HTTP/1.1 200 OK

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/e9b3c1e2-9c48-5b6b-9a88-f55f1d122791 :authority	logs.hivehome-prod.bgchtest.info
accept-encoding	gzip
0000000000 1f 8b 08 00 d7 4b b5 60 00 03 d5 95 5f 6b db 30   .....K.`...._k.0
HTTP/2.0 200 

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxx/attributes/app-settings :authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxx
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxxxxx": 30,
    "lastboostduration-cool-xxxxxxxxxxxxxx": 60,
HTTP/2.0 200 x-amz-cf-idxxxxxxxxxxxxxxxxxxxxxxx
{
    "attribute": "app-settings",
    "value": {
        "feature-usage-devices.settings-changeNameSuccesful": true,
        "feature-usage-heating.settings-changeNameSuccesful": true,
        "first-time-customisation-modal": true,

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxxx/attributes/app-settings
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxx
accept-encoding	gzip
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxxxxxxxxc": 30,
HTTP/2.0 200 via	1.1 669xxxxxxxxxxxxc.cloudfront.net (CloudFront)
x-amz-cf-pop	xxxxxxxxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxx
{
    "attribute": "app-settings",
    "value": {
        "feature-usage-devices.settings-changeNameSuccesful": true,
        "feature-usage-heating.settings-changeNameSuccesful": true,
        "first-time-customisation-modal": true,
        "lastboostduration-xxxxxxxxxxxxxxxxxxx": 30,

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxxxxxxx?homeId=xxxxxxxxxxxxxxx
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxx
{
    "cool": 24,
    "heat": 22.5
}
HTTP/2.0 200 x-amz-cf-pop xxxxxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxx=
{
    "cool": 24,
    "heat": 22.5
}

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxx/attributes/app-settings
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
accept-encoding	gzip
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxxxxxx": 30,
    "lastboostduration-cool-xxxxxxxxxxxxxxxxxxx": 60,
HTTP/2.0 200 {
    "attribute": "app-settings",
    "value": {

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxx/attributes/app-settings
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxx
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
HTTP/2.0 200  {
    "attribute": "app-settings",
    "value": {
        "feature-usage-devices.settings-changeNameSuccesful": true,
        "feature-usage-heating.settings-changeNameSuccesful": true,

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxx?homeId=xxxxxxxxxxxxxx
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxxxxxx
{
    "cool": 23.5,
    "heat": 22
}
HTTP/2.0 200 {
    "cool": 23.5,
    "heat": 22
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxxx
:authority	logs.hivehome-prod.bgchtest.info
accept-encoding	gzip
0000000000 1f 8b 08 00 e4 4b b5 60 00 03 ed 97 cf 6f 9b 30   .....K.`.....o.0
0000000010 14 c7 ef fb 33 38 d7 06 8c 0d 26 d2 34 45 09 6a   ....38....&.4E.j
HTTP/2.0 200 
{}

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxxxxxxx?homeId=xxxxxxxxxxxxxxx
:authority	beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
content-type	application/json
content-length	22
accept-encoding	gzip
{
    "controlMode": "COOL"
}
HTTP/2.0 200 
content-type	application/json;charset=UTF-8
content-length	22
date	xxxxxxxxxxxxx
x-amzn-requestid	xxxxxxxxxxxxxx
access-control-allow-origin	*
x-amz-apigw-id	xxxxxxxxxxxxx
x-amzn-trace-id	Root=1-6xxxxxxxxxxxxx;Sampled=1
x-cache	Miss from cloudfront
via	1.1 xxxxxxxxxxxxxx4c.cloudfront.net (CloudFront)
x-amz-cf-pop	xxxxxxxxxxxxxxx
x-amz-cf-id	xxxxxxxxxxxxxxxxxxxxx
{
    "controlMode": "COOL"
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxx
:authority	logs.hivehome-prod.bgchtest.info
accept-encoding	gzip
0000000000 1f 8b 08 00 f0 4b b5 60 00 03 ed 96 df 6b db 30   .....K.`.....k.0
0000000010 10 c7 df f7 57 14 3d 47 fe ed c4 31 8c 11 e2 b0   ....W.=G...1....
0000000020 e4 61 4d 98 53 06 7b 09 b2 74 8e 4d 63 cb 48 72   .aM.S.{..t.Mc.Hr
HTTP/2.0 200 
{}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxx
 :authority	logs.hivehome-prod.bgchtest.info
user-agent	Hive/10.41.1 Android/xxxxxxxxxxx
content-type	application/vnd.hive.logs.v0+x-ndjson
content-length	176
accept-encoding	gzip
{"event":{"breadcrumb":{"category":"redux-action","level":"info","message":"hive/thermostat/CHANGED_PRODUCT_STATE"},"name":"sentry_breadcrumb"},"ts":"2021-05-31Txxxxxxx6Z"}
HTTP/2.0 200 
{}

**Comment by e46lux** [comment]
@KJonline I'm unable to find async_hive_api.py. I've mitm the login and changing mode. I redacted some identifying information, and apologize for the long dump, but here is what I am seeing (POST, GET and their HTTP responses):

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/exxxxxxxxxxxxxxxxxxx
HTTP/2.0 200

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxx
HTTP/2.0 200

POST https://cognito-idp.eu-west-1.amazonaws.com/ {"ChallengeName":"PASSWORD_VERIFIER","ChallengeParameters":{"SALT":".........."}}

HTTP/2.0 200
:authority cognito-idp.eu-west-1.amazonaws.com
{"AuthFlow":"USER_SRP_AUTH","ClientId":"............

POST https://cognito-idp.eu-west-1.amazonaws.com/ {"ChallengeName":"PASSWORD_VERIFIER","ClientId":"xxxxxxxxxxx","ChallengeResponses":{"USERNAME":"xxxxxxxx","PASSWORD_CLAIM_SECRET_BLOCK":"...."}}}

HTTP/2.0 200 {"AuthenticationResult":{"AccessToken":"....."}

POST https://cognito-idp.eu-west-1.amazonaws.com/
:authority cognito-idp.eu-west-1.amazonaws.com
{"AccessToken":"....."}

HTTP/2.0 200 {"UserAttributes":[{"Name":"sub","Value":"xxxxxxxxx"},{"Name":"zoneinfo","Value":"xxxxxx"},{"Name":"email_verified","Value":"true"},{"Name":"phone_number_verified","Value":"false"},{"Name":"locale","Value":"en_US"},{"Name":"given_name","Value":"Don"},{"Name":"custom:location","Value":"us-east-1"},{"Name":"custom:environment","Value":"de-prod"},{"Name":"email","Value":"xxxxxxxxxx"}],"Username":"xxxxxxxxxxxx"}

GET https://beekeeper-us.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true&user=true&homes=true&homeId authorization
xxxxxxxxxxxxxxxxxxxxxxxxx

HTTP/2.0 200 x-amz-cf-pop xxxxxx
x-amz-cf-id xxxxxxxxxxxxxxx
{
"actions": [],
"alerts": {
"failuresEmail": false,
"failuresSMS": false,
"nightAlerts": false,
"warningsEmail": false,
"warningsSMS": false
},
"devices": [
{
"created": xxxxxxx,
"id": "xxxxxxxxxxxxxxxxxxx",
"lastSeen": xxxxxxxxxxxx,
"parent": "xxxxxxxxxxxxxxxxxxx",
"props": {
"assistedLiving": {
"learning": true,
"nightTime": false,
"noMorningActivity": false,
"noRecentActivity": false
},
"capabilities": [

GET https://beekeeper-us.hivehome.com/1.0/action-templates?version=3 authorization xxxxxxxxxxxxxx accept-encoding gzip

HTTP/2.0 200
x-amz-apigw-id xxxxxxxxxxx
etag xxxxxxxxxxxxa
x-amzn-trace-id Root=1-xxxxxxxxxxxxxx;Sampled=1
access-control-allow-credentials true
x-cache Miss from cloudfront
via 1.1 xxxxxxxxxx.cloudfront.net (CloudFront)
x-amz-cf-pop xxxxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxxxxxxxx
{
"ETag": "xxxxxxxxxxxxxxxxxx",
"modified": "2020-08-18T14:27:22.846Z",
"templates": [
{
"created": 1xxxxxxxxx,
"entitlements": [],

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN0102xxxxx7/s2502xxxxx
Host centricabritishgas.sc.omtrdc.net
Connection Keep-Alive
Accept-Encoding gzip
ndh: 1
pev2: AMACTION:login
ce: UTF-8
ts: xxxxxxxxxxxxxx
c.:
tapMFAToggle.:
status: OFF
.tapMFAToggle:
HTTP/1.1 200 OK xserver anedge-xxxxxxxxxx-w4fdg
access-control-allow-origin *
x-c main-1475.xxxxxxxx.M0-497

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN010xxxxxxxx/s6654xxxxx
ndh: 1
ce: UTF-8
ts: 1xxxxxxxxxx0
c.:
tapMFAToggle.:
status: OFF

HTTP/1.1 200 OK

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxx/attributes/app-settings authorization xxxxxxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop xxxxx
x-amz-cf-id xxxxxxxxxxxxxx
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxx": 30,
"lastboostduration-cool-xxxxxxxx": 60,
"lastboostduration-heat-xxxxxxxxxxx": 60,
"lastboosttarget-cool-xxxxxxxxxx": 23,

GET https://hive-app-service-text.hivehome.net/prod/us.json :authority hive-app-service-text.hivehome.net
HTTP/2.0 404

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxx/attributes/entitlements authorization xxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop xxxxxxxx
x-amz-cf-id xxxxxxxxxxxxxxxx
{
"MimicMode": true,
"flags": {}
}

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxx/attributes/dashboard-config :authority: beekeeper-us.hivehome.com
authorization: xxxxxxxxxxx
HTTP/2.0 404 {
"error": "NOT_FOUND"
}

POST https://api.de-prod.nacho.tech/omnia/deviceTokens/ authorization Bearer xxxxxxxxxxxxxx
{
"deviceTokens": [
{
"appName": "Android_Hive_Live_GCM",
"token": "xxxxxxxxxxxxxx",
"tokenType": "GCM_DATA"
}
]
}
HTTP/2.0 200 server Jetty(9.4.35.v20201120)
{"meta":{},"links":{},"linked":{},"deviceTokens":[{"id":"xxxxxxxxxxxxxx","href":"https://api.de-prod.nacho.tech/omnia/deviceTokens/xxxxxxxxxx","token":"xxxxxxxxxxxx","tokenType":"GCM_DATA","appName":"Android_Hive_Live_GCM"}]}

GET https://hive.bgchprod.info/permission/document?encode=false authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 200 {
"Identities": null,
"Permissions": [
"omnia-api:node:xxxxxxxxxxxxx:MIGRATE_HUB",
"home-service:home:xxxxxxxxxxxx:ADD_EXTERNAL_USER",
"home-service:home:xxxxxxxxxxxx:INVITE_USERS",

GET https://hive.bgchprod.info/home/home/1xxxxxxxxxxxxxa/tariffs authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 200 access-control-allow-credentials true
x-cache Miss from cloudfront
x-amz-cf-pop xxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxxxxxxxxx
{
"home": "xxxxxxxxxxxxxx",
"tariffs": []
}

GET https://hive.bgchprod.info/heating-costs/subscription/xxxxxxxxxxxx authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 403 {
"Message": "There is no subscription to Heating Cost Calculator for homeID xxxxxxxxxxxxxx"
}

GET https://beekeeper-us.hivehome.com/1.0/security-lite?homeId=xxxxxxxxxxxx authorization Bearer xxxxxxxxxxxxxx
HTTP/2.0 404 x-amz-cf-id xxxxxxxxxxxxxxxxxxxxx
{
"error": "NOT_FOUND"
}

POST https://beekeeper-us.hivehome.com/1.0/app-update
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxx
{
"os": 23,
"platform": "react-native-android",
"version": "10.41.1"
}
HTTP/2.0 200 {
"type": "ok"
}

GET https://in-app-sales.hivehome.net/production/config-v3.json
:authority in-app-sales.hivehome.net
HTTP/2.0 200 {
"gb": {
"cacheTTLHours": 1,
"defaultShopUrl": "www.hivehome.com?cid=cen.in-app.in-life....shop",
"deliveryOptions": [
{
"basketTotalMax": 49.99,
"basketTotalMin": 0,
"description": "3-5 working days",
"hasHiveLive": false,
"id": "delivery-1",
"productRatePlanId": "xxxxxxxxxx",
"ratePlanRef": "DEL00005"

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxx/attributes/app-settings :authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxxxxx": 30,
HTTP/2.0 200 x-amz-cf-id xxxxxxxxxxxxxxxx
{
"attribute": "app-settings",
"value": {
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN01xxxxx/sxxxxx4
ndh: 1
ce: UTF-8
ts: xxxxxxxxx
c.:
tapMFAToggle.:
status: OFF
.tapMFAToggle:
accessibility: none
hdl.:
platform.:
environment: production
os: android
version: 10.41.1
technology: react-native
.platform:
user.:
defaultCountry: US
id: xxxxxxxxxxxxx
defaultPostcode: xxxxx
HTTP/1.1 200 OK

GET https://in-app-sales.hivehome.net/production/images.json
:authority in-app-sales.hivehome.net
HTTP/2.0 200 x-amz-cf-id xxxxxxxxxxxxxxxx
{
"accessory/signal_booster/single.png": "https://d3orhbv7fx766b.cloudfront.net/accessory/signal_booster/single-61c4c4af5ec7f464b4219dcea7d078e3b1780fad8bc0d1c9e02f39453d838380.png",

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxxxxx
:authority logs.hivehome-prod.bgchtest.info
accept-encoding gzip
0000000000 1f 8b 08 00 c1 4b b5 60 00 03 dd 5a 5b 73 a3 36 .....K.`...Z[s.6
HTTP/2.0 200 apigw-requestid xxxxxxxx

GET https://hive.bgchprod.info/home/owner/xxxxxxxx/home/id/xxxxxxx
authorization Bearer xxxxxxxxxxxxxxx
HTTP/2.0 200 x-amz-cf-pop xxxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxxxx
{
"address": "xxxxxxxxxxxxxx",
"environment": "prod-us",
"home": "xxxxxxxxxxxxxxxx",
"homePhase": "Live",
"homePicture": null,
"homeTypes": [
"HIVE"
],
"homeUsers": {
"OWNER": [
"xxxxxxxxxx"

GET https://hive.bgchprod.info/home/home/xxxxxxxxxx/user_access
authorization Bearer xxxxxxxxxxxxxxx
HTTP/2.0 200
{
"disarmSchedules": {},
"home": "xxxxxxxxxxxxx",
"permissionPolicies": {
"xxxxxxxxxxxxx": []
},
"pinIds": {
"xxxxxxxxxxxxxxxx": null
},
"pins": {}
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxx
HTTP/2.0 200

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxx?homeId=xxxxxxxx
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxx
{
"controlMode": "AUTO"
}

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN0102xxxx/s5xxxxxxx Host centricabritishgas.sc.omtrdc.net
ndh: 1
ce: UTF-8
ts: xxxxxxxx
c.:
tapMFAToggle.:
status: OFF
HTTP/1.1 200 OK

POST https://centricabritishgas.sc.omtrdc.net/b/ss/cbghivereactnativeprod/0/ANDN01020xxxxx/sxxxxx Host centricabritishgas.sc.omtrdc.net
ndh: 1
ce: UTF-8
ts: 162xxxxxx
c.:
tapMFAToggle.:
status: OFF
HTTP/1.1 200 OK

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxx :authority logs.hivehome-prod.bgchtest.info
accept-encoding gzip
0000000000 1f 8b 08 00 d7 4b b5 60 00 03 d5 95 5f 6b db 30 .....K.`...._k.0
HTTP/2.0 200

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxx/attributes/app-settings :authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxx
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxx": 30,
"lastboostduration-cool-xxxxxxxxxxxxxx": 60,
HTTP/2.0 200 x-amz-cf-idxxxxxxxxxxxxxxxxxxxxxxx
{
"attribute": "app-settings",
"value": {
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxxx/attributes/app-settings
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxx
accept-encoding gzip
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxxxxxc": 30,
HTTP/2.0 200 via 1.1 669xxxxxxxxxxxxc.cloudfront.net (CloudFront)
x-amz-cf-pop xxxxxxxxxxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxxxx
{
"attribute": "app-settings",
"value": {
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxxxxxxxxxx": 30,

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxxxxxxx?homeId=xxxxxxxxxxxxxxx
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxx
{
"cool": 24,
"heat": 22.5
}
HTTP/2.0 200 x-amz-cf-pop xxxxxxxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxx=
{
"cool": 24,
"heat": 22.5
}

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxx/attributes/app-settings
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
accept-encoding gzip
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
"first-time-customisation-modal": true,
"lastboostduration-xxxxxxxxxxxx": 30,
"lastboostduration-cool-xxxxxxxxxxxxxxxxxxx": 60,
HTTP/2.0 200 {
"attribute": "app-settings",
"value": {

POST https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxxxxxxxxx/attributes/app-settings
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxx
{
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,
HTTP/2.0 200 {
"attribute": "app-settings",
"value": {
"feature-usage-devices.settings-changeNameSuccesful": true,
"feature-usage-heating.settings-changeNameSuccesful": true,

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxx?homeId=xxxxxxxxxxxxxx
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxxxxxxxxxx
{
"cool": 23.5,
"heat": 22
}
HTTP/2.0 200 {
"cool": 23.5,
"heat": 22
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxxx
:authority logs.hivehome-prod.bgchtest.info
accept-encoding gzip
0000000000 1f 8b 08 00 e4 4b b5 60 00 03 ed 97 cf 6f 9b 30 .....K.`.....o.0
0000000010 14 c7 ef fb 33 38 d7 06 8c 0d 26 d2 34 45 09 6a ....38....&.4E.j
HTTP/2.0 200
{}

POST https://beekeeper-us.hivehome.com/1.0/nodes/nathermostat/xxxxxxxxxxxxxxx?homeId=xxxxxxxxxxxxxxx
:authority beekeeper-us.hivehome.com
authorization xxxxxxxxxxxx
content-type application/json
content-length 22
accept-encoding gzip
{
"controlMode": "COOL"
}
HTTP/2.0 200
content-type application/json;charset=UTF-8
content-length 22
date xxxxxxxxxxxxx
x-amzn-requestid xxxxxxxxxxxxxx
access-control-allow-origin *
x-amz-apigw-id xxxxxxxxxxxxx
x-amzn-trace-id Root=1-6xxxxxxxxxxxxx;Sampled=1
x-cache Miss from cloudfront
via 1.1 xxxxxxxxxxxxxx4c.cloudfront.net (CloudFront)
x-amz-cf-pop xxxxxxxxxxxxxxx
x-amz-cf-id xxxxxxxxxxxxxxxxxxxxx
{
"controlMode": "COOL"
}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxx
:authority logs.hivehome-prod.bgchtest.info
accept-encoding gzip
0000000000 1f 8b 08 00 f0 4b b5 60 00 03 ed 96 df 6b db 30 .....K.`.....k.0
0000000010 10 c7 df f7 57 14 3d 47 fe ed c4 31 8c 11 e2 b0 ....W.=G...1....
0000000020 e4 61 4d 98 53 06 7b 09 b2 74 8e 4d 63 cb 48 72 .aM.S.{..t.Mc.Hr
HTTP/2.0 200
{}

POST https://logs.hivehome-prod.bgchtest.info/v0/devices/xxxxxxxxxxxxxxxxxxx
 :authority logs.hivehome-prod.bgchtest.info
user-agent Hive/10.41.1 Android/xxxxxxxxxxx
content-type application/vnd.hive.logs.v0+x-ndjson
content-length 176
accept-encoding gzip
{"event":{"breadcrumb":{"category":"redux-action","level":"info","message":"hive/thermostat/CHANGED_PRODUCT_STATE"},"name":"sentry_breadcrumb"},"ts":"2021-05-31Txxxxxxx6Z"}
HTTP/2.0 200
{}

**Comment by KJonline** [comment]
Thanks for that, most the calls are the same as the uk api with just the host changing to add the us bit. The one api call I can’t see is the refresh token and it’s where I think the integration is failing. You don’t need to do step 1 if you haven't opened the app in over 2 hours already.

1) Please can your open the app on your phone, wait an hour or 2.  

2) setup the mitm setup again without opening the app

3) once it’s setup then open the app on your phone. 

4) This should capture the token refresh request

**Comment by e46lux** [comment]
@KJonline thanks so much! I believe this is what you requested:

GET https://hive-app-service-text.hivehome.net/prod/us.json HTTP/2.0
:authority	hive-app-service-text.hivehome.net
accept-encoding	gzip
user-agent	okhttp/3.14.3
if-none-match	"xxxxxxxxxxxxxxxxx"

HTTP/2.0 404 
etag	"xxxxxxxxxxx"
x-cache	Error from cloudfront
via	1.1 xxxxxxxxxxxxxx.cloudfront.net (CloudFront)
x-amz-cf-pop	xxxxx-xx
x-amz-cf-id	xxxxxxxxxxxx


POST https://cognito-idp.eu-west-1.amazonaws.com/ HTTP/2.0
:authority	cognito-idp.eu-west-1.amazonaws.com
x-amz-target	AWSCognitoIdentityProviderService.InitiateAuth
x-amz-user-agent	aws-amplify/0.1.x react-native
content-type	application/x-amz-json-1.1
content-length	3367
accept-encoding	gzip
user-agent	okhttp/3.14.3
{"ClientId":"xxxxxxxxx","AuthFlow":"REFRESH_TOKEN_AUTH","AuthParameters":{"REFRESH_TOKEN":"xxxxxxxx...xxx"}}

HTTP/2.0 200 
date	Thu, 03 Jun 2021 12:34:49 GMT
content-type	application/x-amz-json-1.1
content-length	2283
x-amzn-requestid	xxxxxxxx
{"AuthenticationResult":{"AccessToken":"xxxxxxx","ExpiresIn":3600,"IdToken":"xxxxx","TokenType":"Bearer"},"ChallengeParameters":{}}

POST https://beekeeper-us.hivehome.com/1.0/app-update HTTP/2.0
:authority	beekeeper-us.hivehome.com
user-agent	Hive/10.41.1 Android/6.0.1
authorization	xxxxxxxxxxxxx
content-type	application/json
content-length	63
accept-encoding	gzip
{
    "os": 23,
    "platform": "react-native-android",
    "version": "10.41.1"
}

GET https://beekeeper-us.hivehome.com/1.0/user/xxxxxxxx/attributes/app-settings HTTP/2.0
:authority	beekeeper-us.hivehome.com
user-agent	Hive/10.41.1 Android/6.0.1
content-type	application/json
authorization	xxxxxxxxx
accept-encoding	gzip

HTTP/2.0 200 
content-type	application/json;charset=UTF-8
content-length	785
date	Thu, 03 Jun 2021 12:34:50 GMT
x-amzn-requestid	xxxxxxxx
access-control-allow-origin	*
x-amz-apigw-id	xxxxxxxx
x-amzn-trace-id	Root=1-xxxxxxxx-xxxxxxxx;Sampled=0
access-control-allow-credentials	true
x-cache	Miss from cloudfront
via	1.1 0bxxxxxxxx5a0.cloudfront.net (CloudFront)
x-amz-cf-pop	xxxxxxxx
x-amz-cf-id	xxxxxxxx
{
    "feature-usage-devices.settings-changeNameSuccesful": true,
    "feature-usage-heating.settings-changeNameSuccesful": true,
    "first-time-customisation-modal": true,
    "lastboostduration-xxxxxxxx": 30,
    "lastboostduration-cool-xxxxxxxx": 60,
    "lastboostduration-heat-xxxxxxxx": 60,
    "lastboosttarget-cool-xxxxxxxx": 23,
    "lastboosttarget-heat-xxxxxxxx": 24.5,
    "manual-target-value-xxxxxxxx-auto-cool": 23.5,
    "manual-target-value-xxxxxxxx-auto-heat": 22,
    "manual-target-value-xxxxxxxx-cool-cool": 24.5,
    "manual-target-value-xxxxxxxxx-heat-heat": 24,
    "mfa-enabled": false
}

**Comment by KJonline** [comment]
Yep that's spot on and why its not working for US, the refresh token URL is going back to AWS where as in the UK version it goes to the beekeeper domain to refresh the token.

**Comment by e46lux** [comment]
@KJonline are there URLs I can manually change after installing the integration through HACS or after setting up the integration in home assistant to get it to work? Or will you be making adjustments to the integration to expand and allow US tenants to work? Thank you!

**Comment by KJonline** [comment]
Thanks for the examples from the app. I have made a change to the api now which supports the refresh token example you mentioned above, it will be in the next pyhiveapi release 4.3

**Comment by KJonline** [comment]
I have released 2021.5.5 of the custom component which should fix the refresh token issue. I think there will be more issues during setup though for data structure issues

**Comment by e46lux** [comment]
@KJonline thank you so much for your hard work! It seems like 2021.5.5 does not yet show up in HACS, although I can see it here on github. I attempted re-installing the repo, with and without beta checked and still not showing up. Is there something on my side I need to adjust to give it a go?

**Comment by KJonline** [comment]
Ye I had to pull the release because of this issue I’m going to have another go tonight and see what I’m doing wrong

**Comment by e46lux** [comment]
Hi, @KJonline. Hope all is well! Was wondering if you had some time to re-visit this issue? I can provide any additional info you may request - if you'd like full logs, etc. Cheers!

**Comment by gary-sargent** [comment]
Isn't the US tenant being turned off at the end of this month? See https://www.hivehome.com/us/support
